### ISSUE TITLE
Reimplement the sticks as a server-side variant

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#10]
# Description

Currently the Stick items are implemented with a dedicated item. This requires this mod to be installed at the client side. To remove this limitation, the sticks needs to be implemented only with vanilla features.

A possible solution would be to use the default minecraft stick, blaze rod or end rod and mark them with NBT data defining their stick type and thus their features. 

Stick type can be checked when triggering actions like left or right-click.

# Todos

- Define NBT data to be saved for sticks
- Implement classes for different sticks 
- Implement `StickInteractionHandler` to subscribe to events (`RightClickBlock`, `RightCLickItem`, `AnvilRepairEvent`) 
- Implement handler to create regions when renaming the RegionMarker
- Implement handler to create the different Sticks by using the corresponding identifier
- Implement handler to cycle stick modes
- Make mod sticks glow to distinguish them from normal sticks
- Add tooltips to sticks
- Implement skeleton StickHandler for different Sticks

# Definition of Done

- [x] Sticks hold information about their type
- [x] Implemented classes for different sticks
- [x] Sticks have an enchantment glint
- [x] Sticks show their tooltips accordingly
- [x] Implemented handler to create regions
- [x] Implemented handler to create different sticks
- [x] Implemented handler to cycle stick modes for different sticks
- [x] Implemented skeleton StickHandler for different sticks
