### ISSUE TITLE
feat: WorldEdit integration

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#114]
# Optional WorldEdit integration

This feature would replace the RegionMarker for marking areas to create Local Regions. 

Without using the optional WE integration, there is no RegionMarker available. Creating regions is then only possible using the CLI.

# TODOs

- [ ] CLI integration to select area for WE modification and save it after
- [ ] CLI integration to create Region with selected area from WE
- [ ] CLI integration to visualize the area of a region
- [ ] ...

# Related Issues

- #6 
- #31 
- #32 
- #9
- #60

**Comment by petersv5** [comment]
Want me to do a version for the new multi-loader version of YAWP?

**Comment by Z0rdak** [comment]
I need to update the issue description.. 
but i’d be very grateful for at least a prototype which I can use for a full implementation.

**Comment by Z0rdak** [comment]
Note:
WorldEdit availability is limited and only matches a subset of YAWP releases.

WE is available for:

- 1.20.1    => Forge, Fabric
- 1.21.1+  => Neoforge, Fabric

YAWP dropped Forge support since 1.21.6 anyway due to big changes to Forge's event bus system.
