### ISSUE TITLE
Rework the region definition and hierarchy

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#14]
# Description

The previous definition of regions is solid and works fine, but very limiting. To enable more flexibility, the region definition needs to be redesigned.

# Todos

- Create interface to abstract methods for different types of regions
- Define regions without an actual area: `DimensionalRegion` (regions for dimensions)
- Define an abstraction for 'markable' regions, which have a defined area
- Define a region hierarchy for regions (parent and child regions)
- Define an abstraction for the actual area to have an interface to work with when managing the area of a region
- Define blacklist/whitelist property for flags
- Define different types of regions and their area abstractions and create issues
- Define an abstraction for members and owners for a region as well as (vanilla teams) teams
- Implement region hierarchy checks (parent/childs)
- Add Wiki entry for region hierarchy

# Definition of Done

- [x] Implemented an interface to define markable regions and regions without area
- [x] Implemented dimensional regions for dimensions
- [x] Implemented a working region hierarchy 
- [x] Implemented abstraction for region areas
- [x] Defined different types of regions and areas and created separate issues for them
- [x] Implemented an abstraction for Members and Owners (players and teams)
- [x] Implemented working region hierarchy checks
- [ ] Added wiki entry explaining region hierarchy and its constraints

**Comment by Z0rdak** [comment]
Follow up: 
- Double check and implement region hierarchy consistency
- Implement CLI for local regions

**Comment by Z0rdak** [comment]
/Close
Wiki entries will have an own issue
