### ISSUE TITLE
Re-Implement RegionMarker

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#24]
# Description

The RegionMarker stick was and is used to mark blocks for a region area. To support different region shapes, the Marker needs to be redesigned.

# Todos

- Define region shapes
- Define NBT data to be hold by the `MarkerStick`
- Implement marking of different region types
- Implement the marking of a teleport position

# Definition of Done

- [x] Implemented regions shapes 
- [x] MarkerStick saves the marked blocks
- [x] MarkerStick saves the teleport position
- [x] MarkerStick holds the type of area
- [x] Implemented cycling of area types
- [x] Implemented handler to mark blocks
- [x] Implemented region creation from marked blocks and area type
- [x] Created region is saved in world data
