### ISSUE TITLE
Re-Implement FlagStick

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#25]
# Description

The FlagStick is used to add and remove to add region in combination with a selected region from the RegionStick. Additionally, it can be used at a chest containing name tags named like flags to add or remove the flags all at once.
 
- Cycling of flags (this is maybe a feature for deprecation - to many flags make selecting flags with the stick a tedious task)

# Todos

- Implement cycling of modes (add, remove)
- Implement adding and removing of name tags in containers as flags 
- [Maybe] Implement a command to add/remove multiple flags from containers

# Definition of Done

- [x] Define NBT data to be saved
- [x] Implemented handler for switching stick modes
- [ ] Flags can be added/removed with name tags in containers

**Comment by Z0rdak** [comment]
/close
Will not be implemented (in this way). There are far too many flags to make this easy to use.
