### ISSUE TITLE
Implement SphericalRegion and Area

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#29]
# Description

# Todos

## `SphereArea`
- Implement structure to save block info
- Implement contains check
- Implement serialization
- Implement `toString()` for CLI info

## `SphereRegion`
- Implement constructors using the SphereArea
- Implement other methods (contains/serialization)

# Definition of Done

## SphereArea
- [x] Area is implemented with SPHERE type
- [x] Area saves block info in fitting format
- [x] Implemented `contains(Blockpos)` method
- [x] Implemented `toString()` method
- [x] Implemented serialization

## SphereRegion
- [x] Implemented constructors using SphereArea
- [x] Implemented other misc methods
