### ISSUE TITLE
Implement CuboidRegion and Area

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#30]
# Description

# Todos

## `CuboidArea`
- Implement structure to save block info
- Implement contains check
- Implement serialization
- Implement `toString()` for CLI info

## `CuboidRegion`
- Implement constructors using the CuboidArea
- Implement other methods (contains/serialization)

# Definition of Done

## CuboidArea
- [x] Area is implemented with CUBOID type
- [x] Area saves block info in a AxisAlignedBB
- [x] Implemented `contains(Blockpos)` method
- [x] Implemented `toString()` method
- [x] Implemented serialization

## CuboidRegion
- [x] Implemented constructors using CuboidArea
- [x] Implemented other misc methods
