### ISSUE TITLE
Implement PrismRegion and Area

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#31]
# Description

# Todos

## `PrismArea`
- Implement structure to save block info
- Implement contains check
- Implement serialization
- Implement `toString()` for CLI info

## `PrismRegion`
- Implement constructors using the PrismArea
- Implement other methods (contains/serialization)

# Definition of Done

## PrismArea
- [x] Area is implemented with PRISM type
- [ ] Area saves block info in fitting format
- [ ] Implemented `contains(Blockpos)` method
- [ ] Implemented `toString()` method
- [ ] Implemented serialization

## PrismRegion
- [x] Implemented constructors using PrismArea
- [x] Implemented other misc methods

**Comment by Z0rdak** [comment]
New local region shapes are on hold for now to focus on other, more relevant features.
