### ISSUE TITLE
Implement CylinderRegion and Area

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#32]
# Description

# Todos

## `CylinderArea`
- Implement structure to save block info
- Implement constructors
- Implement contains check
- Implement serialization
- Implement `toString()` for CLI info

## `CylinderRegion`
- Implement constructors using the CylinderArea
- Implement other methods (contains/serialization)

# Definition of Done

## CylinderArea
- [x] Area is implemented with CYLINDER type
- [x] Area is saved as block, radius and distance 
- [x] Implemented `contains(Blockpos)` method
- [x] Implemented `toString()` method
- [x] Implemented serialization

## CylinderRegion
- [x] Implemented constructors using CylinderArea
- [x] Implemented other misc methods
