### ISSUE TITLE
Implement Polygon3DRegion and Area 

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#33]
# Description

# Todos

## `Polygon3DArea`
- Implement structure to save block info
- Implement contains check
- Implement serialization
- Implement `toString()` for CLI info

## `PolygonRegion`
- Implement constructors using the Polygon3DArea
- Implement other methods (contains/serialization)

# Definition of Done

## Polygon3DArea
- [x] Area is implemented with POLYGON3D type
- [x] Area saves block info in fitting format
- [x] Implemented `contains(Blockpos)` method
- [ ] Implemented `toString()` method
- [x] Implemented serialization

## PolygonRegion
- [x] Implemented constructors using Polygon3DArea
- [x] Implemented other misc methods

**Comment by Z0rdak** [comment]
This area type will be pushed back. First the other area types in combination with WorldEdit will be implemented
