### ISSUE TITLE
Display surrounding region names

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#47]
# Overview

To have an easier overview of regions the player stands in, it would be great to have an indicator.

# Todo

* Use vanilla item with special tag to execute command on right click
* Make vanilla item configurable
* Add event handler to trigger command
* Add command to display regions around command issuer

# Definition of Done

* [ ] Choosen default item to use 
* [ ] Added event handler to fright click and check for item
* [ ] Added custom tag to check against
* [ ] Add config with validator for item to use

**Comment by Z0rdak** [comment]
In WP this was possible with `/wp region list` but would only display the regions in chat. 
Another solution would be to bundle these kinds of features in a separate QoL mod which is not server-side only.

**Comment by IVEN2022** [comment]
When you Enter A region , a Region name will be displayed in red color or anycolor on the hotbar for few seconds then disapear

**Comment by Z0rdak** [comment]
Messages for leaving and entering regions are tied to another feature. A trigger system for entering and leaving regions. Which is planned to be used to show messages as well for other purposes (executing commands for example).
See: #11

**Comment by Z0rdak** [comment]
As a first approach to solve this issue, it would be possible to use an existing vanilla item and add a custom tag which is checked when using the item. Similar to the RegionMarker.
This way, a command can executed to prompt the regions around the user.

**Comment by Z0rdak** [comment]
Closed. Planned to be added in #6
