### ISSUE TITLE
RegionMarker improvements

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#6]
# Description

Currently, the RegionMarker works/is used for marking Cuboid Regions in conjunction with the `/wp marker create` command to define a new Local Region. 

The well known expand command from WorldProtector only works while creating a new region with the marker. The goal is to expand the region area more easily for already defined regions, supporting the new different shapes.

The 1.16.5 branch of WorldProtector also used the RegionMarker to set the teleport position of the region. This needs to be implemented as well for easier management. 

This feature should also consider the future region shapes, so a proper abstraction is needed.

To be more flexible, it would be great to make the RegionMarker a configurable item, to avoid incompatibilities with other mods.
E.g. The Supplementaries mod has a feature which allows for Sticks to be placed, which renders the RegionMarker useless.

Additionally, to avoid duplicating items and giving players advantage, there should only be one RegionMarker allowed at a time for a player. This prevents the `/wp marker give` command to provide the player with free items.

# Todos

- [ ] Create an interface method to change the size for expanding the area based on the `AreaType`
- [ ] Add CLI support for resizing the area of a Local Region (changing area by defining new positions, already works. This is about easy resizing)
- [ ] Add RegionMarker functionality to select a (owned) Local Region for management
- [ ] Add RegionMarker functionality to set the teleport position of a Local Region
- [ ] Add command to select a Local Region
- [ ] Add command to list nearby regions (will be replaced later by a visual indicator)
- [ ] Add expand command
- [ ] Add RegionMarker functionality to expand/change the size of the selected Local Region
- [ ] Add option to make the item of the RegionMarker configurable
- [ ] Make the RegionMarker unique per Player

# Related Issues

- #47

**Comment by Z0rdak** [comment]
IF this feature will be added to an item, it will be the RegionMarker; the RegionStick is gone for good.

**Comment by Z0rdak** [comment]
Closed and on hold.
By adding a optional WorldEdit integration, this feature would become obsolete.

WorldEdit provides a way to 
- mark, extend, etc. areas.
- configure the used marker item
- partial region visualization
- ...
