### ISSUE TITLE
feat: New Flag Suggestions

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#66]
# Overview for Flag suggestions

Following is a list of flag suggestions which may or may not be implemented. These flags are in no particular order.

## Environment

- [x] lightning-fire-spread (currently included in lightning flag)
- [x] lightning-power-rods (currently included in lightning flag)
- [x] lightning-oxidation-removal (currently included in lightning flag)
- [x] snow-smelting
- [x] snow-fall
- [x] leaf-decay
- [x] frostwalker-freeze
- [x] fire-spread
- [x] water-flow
- [x] lava-flow
- [x] fluid-flow
- [ ] spawn-warden
- [ ] saplings-growth
- [ ] apply-effects-negative
- [ ] apply-effects-positive
- [ ] ice-freezing
- [ ] shovel-extinguish-fire
- [ ] lectern-take-book

## Game-Mechanic

- [x] ~~no-hunger~~ (temp removed)
- [x] keep-inventory
- [x] keep-xp
- [x] use-bows
- [x] use-crossbow
- [ ] wax-blocks
- [ ] scrape-wax
- [ ] shulker-shrieking
- [ ] shulker-activating
- [ ] moss-spreading
- [ ] piston-pull
- [ ] piston-push
- [ ] keep-equipment
- [ ] keep-hotbar
- [ ] use-potions
- [ ] use-food
- [ ] use-chorus-tp
- [ ] use-spyglass
- [ ] use-horn
- [ ] use-trident
- [ ] hunger-loss
- [ ] durability-loss
- [ ] villager-breeding
- [ ] windcharge-trigger
- [ ] block-falling

## Misc

- [x] no-item-despawn
- [x] projectile-defense
- [ ] flag for spawners and eggs separate from normal spawning
- [ ] mob-pickup-item (mobs pickup logic => MobEntity#livingTick)
- [ ] block-blacklist (see #113 )
- [ ] item-blacklist (see #113 )
- [ ] spawn-blacklist (see #113 )
- [ ] entry-blacklist (see #113 )
- [ ] leave-blacklist (see #113 )
- [ ] use-chat

**Comment by Z0rdak** [comment]
# 1.20 Flag Suggestions

- [ ] amethyst-repeat-skulk-signal

**Comment by funnycubeguy** [comment]
Can you add a flag that lets you enter a specific mob to prevent spawning? thankz

**Comment by Z0rdak** [comment]
@funnycubeguy that will be part of the next bigger feature: #113

**Comment by MagnusHJensen** [comment]
Are these flags something people can contribute to code-wise?

**Comment by Z0rdak** [comment]
Sure, I'd appreciate it.
I'd appreciate even more If new flag contributions would consider both forge and fabric, so I can keep flag consistency across loaders.

**Comment by TheRedXD** [comment]
Add a flag to prevent blocks from falling

**Comment by DoodeJr** [comment]
Not sure if I'm blind, but if there isn't a way to already a flag to allow the use of waystones from the popular Waystones mod.
