### ISSUE TITLE
Global Region

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#67]
# Description

Beside Local and Dimensional Regions, there are some flags you would want to define for the whole server, so globally.

This could be done with a global region, known from plugins like WorldGuard.

# Todos

- [x] Implement Type for Global Region
- [x] Add Global Region saving/loading
- [x] Add configuration for the Global Region
- [x] Add CLI support to manage the Global Region
- [x] Update Flag permissions by including the Global Region

**Comment by Z0rdak** [comment]
Will be released with 0.0.4.0-beta1
