### ISSUE TITLE
Flag system improvements

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#69]
# Description

Negation of flags is needed to make child regions overwrite the flag permissions of their parent/overlapping regions.

# Todos

- [x] Add CLI support to negate flags
- [x] Rework flag permission check to include flag overriding
- [x] Flag/Region inheritance
- [x] Consider global region

# Related Issues

- #17 
- #48 
- #39 
- #67 
- #78

**Comment by Z0rdak** [comment]
Will be released with 0.0.4.0-beta1
