### ISSUE TITLE
Add command to copy flags from a region

### ISSUE THREAD

**Issue by Z0rdak** [Z0rdak/Yet-Another-World-Protector#79]
# Description

To make setting up regions more easy it would be nice to be able to copy flags from existing regions.

# Todo

- [x] Add command to copy the flags from a local region to another
- [x] Add command to copy the state from a local region to another
- [x] Add command to copy the players from a local region to another
- [x] Add command to copy the flags from a dimensional region to another
- [x] Add command to copy the state from a dimensional region to another
- [x] Add command to copy the players from a dimensional region to another
- [x] Regions suggested should only be owned regions, to prevent copying flags from foreign regions (this would leak to added flags of regions from other players)
- [x] Add language keys

**Comment by Z0rdak** [comment]
Follow up: Extend copy command to other properties like

- state
- affiliations
- ...

**Comment by Z0rdak** [comment]
Copy teams and affiliation won't be added with this issue.
This will have to wait until LuckPerms integration is implemented
